# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f0ad3b3450ee5961fdaf08aa5f85372b7f1192dbfddf74a587eec4b1ade6bd000c6ee5b69d671112c454c3ea6f171bc7b3b233f8d8c85e9f9f9b7cbaa6cf010

test:
  secret_key_base: dd2ee2d5ca2145dbba2b21816b841dfef42cab7eae712436c88f9e78a5d3eaf0f1d8b84ab63588f98a38ae5ab858f0f36a95f80aa3d4dc3ba2b2f7e0e7b2c9ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
